
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          ./mvnw package
          tar -czvf tarball.tar.gz ./target
      - name: Upload tarball
        uses: actions/upload-artifact@v3
        with:
          name: tarball
          path: ${{ github.workspace }}/tarball.tar.gz
  docker:
    runs-on: ubuntu-18.04
    needs: [ build ]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v1
      - name: Download executable
        uses: actions/download-artifact@v3
        with:
          name: tarball
      - name: untar and move to docker dir
        run: |
          tar -xvzf tarball.tar.gz
          mv ./target/quarkus-app ./docker
          cd docker
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }}
          -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          cd docker
          docker build --build-arg DD_API_KEY=${{ secrets.DATADOG_API_KEY }} -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image with commit sha tag
        run: docker push $REPO:${GITHUB_SHA::8}
      - name: Publish Docker image with tag latest
        run: docker push $REPO:latest